"""Add url field to store team url

Revision ID: 80c61d664563
Revises: 0611bed9f994
Create Date: 2019-06-28 17:30:43.295722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c61d664563'
down_revision = '0611bed9f994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('url', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_team_url'), 'team', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_url'), table_name='team')
    op.drop_column('team', 'url')
    # ### end Alembic commands ###
